<?php
$diccionario = array(
    "hello" => "hola",
    "goodbye" => "adiós",
    "please" => "por favor",
    "thank you" => "gracias",
    "sorry" => "lo siento",
    "yes" => "sí",
    "no" => "no",
    "man" => "hombre",
    "woman" => "mujer",
    "child" => "niño",
    "dog" => "perro",
    "cat" => "gato",
    "house" => "casa",
    "car" => "coche",
    "book" => "libro",
    "water" => "agua",
    "food" => "comida",
    "school" => "escuela",
    "teacher" => "profesor",
    "student" => "estudiante",
    "city" => "ciudad",
    "country" => "país",
    "day" => "día",
    "night" => "noche",
    "love" => "amor",
    "friend" => "amigo",
    "work" => "trabajo",
    "money" => "dinero",
    "family" => "familia",
    "happiness" => "felicidad"
);
?>